import { Product, Category } from '@/types';

export const CATEGORIES: Category[] = [
  {
    id: 'sculptures',
    name: 'Sculptures',
    slug: 'sculptures',
    description: 'Classical masterworks, figurative bronzes and antique stone carvings.',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    itemCount: 42,
  },
  {
    id: 'wall-decor',
    name: 'Wall Decor',
    slug: 'wall-decor',
    description: 'Hand-carved mandalas, historic architectural friezes and gilded medallions.',
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
    itemCount: 28,
  },
  {
    id: 'vases-planters',
    name: 'Vases & Planters',
    slug: 'vases-planters',
    description: 'Fluted amphora urns, patinated pottery and imperial ceramic vessels.',
    image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
    itemCount: 35,
  },
  {
    id: 'lighting',
    name: 'Lighting',
    slug: 'lighting',
    description: 'Bespoke sculptural luminaires, solid brass sconces and warm glowing pendants.',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80',
    itemCount: 19,
  },
  {
    id: 'table-decor',
    name: 'Table Decor',
    slug: 'table-decor',
    description: 'Hammered ritual bowls, antique candelabras and ceremonial accents.',
    image: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=800&q=80',
    itemCount: 31,
  },
  {
    id: 'custom-designs',
    name: 'Custom Designs',
    slug: 'custom-designs',
    description: 'Bespoke commissions handcrafted to exact architectural dimensions.',
    image: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=800&q=80',
    itemCount: 12,
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'lux-01',
    name: 'Handcrafted Heritage Vase',
    slug: 'handcrafted-heritage-vase',
    subtitle: '19th Century Hellenistic Acanthus Amphora',
    description: 'A premium handcrafted antique vase with intricate detailing, perfect for luxury home decor.',
    longDescription: 'Cast in heavy bronze with hand-chiselled acanthus leaves and classical relief vignettes, the Heritage Vase embodies 19th-century European revivalist artistry. Finished with an antiqued verdigris and brushed gold patina, this statement piece elevates consoles, credenzas, and library alcoves.',
    story: 'Meticulously shaped using lost-wax casting methods preserved through generations of Florence metallurgists, every fluted curve reflects intentional, time-honored patience.',
    price: 12500,
    compareAtPrice: 15800,
    category: 'Vases & Planters',
    categorySlug: 'vases-planters',
    collection: 'Imperial Heritage',
    images: [
      '/images/heritage-vase.jpg',
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=1000&q=80',
    ],
    model3D: {
      type: 'vase',
      color: '#8c6d46',
      roughness: 0.38,
      metalness: 0.85,
      scale: 1.1,
    },
    material: 'Cast Bronze & Gold Foil Leaf',
    dimensions: '34cm H x 22cm W x 18cm D',
    weight: '6.4 kg',
    origin: 'Tuscany, Italy (Archival Reproduction)',
    era: 'Late 19th Century Style',
    stock: 7,
    rating: 4.9,
    reviewsCount: 38,
    featured: true,
    bestseller: false,
    isNew: false,
    limited: true,
    handcrafted: true,
    tags: ['Amphora', 'Bronze', 'Acanthus', 'Featured 3D', 'Vase'],
    specifications: {
      'Craft Technique': 'Lost-Wax Cast & Hand Engraved',
      'Finish': 'Antiqued Burnished Bronze with Gold Highlights',
      'Care': 'Wipe clean with a soft microfiber cloth; avoid acidic cleaners',
      'Waterproof': 'Dry ornamental use recommended',
    },
  },
  {
    id: 'lux-02',
    name: 'Antique Royal Stallion Sculpture',
    slug: 'antique-royal-stallion-sculpture',
    subtitle: 'Majestic Equestrian Bronze on Nero Marquina Base',
    description: 'An iconic antique bronze horse statue with ornamental bridle and hand-embossed parade harness.',
    longDescription: 'Capturing noble equine poise and classical anatomy, the Royal Stallion is a monument to nobility. Perched atop a bevelled black Nero Marquina marble block, the oxidized bronze boasts warm amber undertones and tactile surface depth.',
    story: 'Inspired by ceremonial cavalries of the Austrian court, this bronze was cast with precision contours to catch ambient afternoon light across its muscular shoulders and tailored harness.',
    price: 28500,
    compareAtPrice: 34000,
    category: 'Sculptures',
    categorySlug: 'sculptures',
    collection: 'Noble Equine',
    images: [
      '/images/hero-horse.jpg',
      'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1569683795645-b62e50fbf103?auto=format&fit=crop&w=1000&q=80',
    ],
    model3D: {
      type: 'sculpture',
      color: '#7a5a3a',
      roughness: 0.32,
      metalness: 0.9,
      scale: 1.0,
    },
    material: 'Heavy Patinated Bronze & Nero Marquina Marble',
    dimensions: '48cm H x 36cm W x 19cm D',
    weight: '14.2 kg',
    origin: 'Vienna, Austria',
    era: 'Neoclassical Revival',
    stock: 3,
    rating: 5.0,
    reviewsCount: 46,
    featured: true,
    bestseller: false,
    isNew: true,
    limited: true,
    handcrafted: true,
    tags: ['Horse', 'Bronze', 'Hero Piece', 'Marble', 'Sculpture'],
    specifications: {
      'Base': 'Solid Natural Black Veined Marble',
      'Weight Class': 'Heavily Weighted Center of Gravity',
      'Certificate': 'Includes Hand-Numbered Heritage Certificate',
    },
  },
  {
    id: 'lux-03',
    name: 'Serene Gautama Buddha Bust',
    slug: 'serene-gautama-buddha-bust',
    subtitle: 'Weathered Bronze Sanctuary Head with Gold Patina',
    description: 'A tranquil meditative bronze bust with serene expression and aged verdigris highlights.',
    longDescription: 'Radiating calm introspection and spiritual grace, this sculpted bust features elongated earlobes, traditional ushnisha curls, and downcast contemplative eyes. Soft candlelight illuminates subtle gold-leaf remnants beneath its bronze patina.',
    story: 'Cast using ancient Southeast Asian wax molds, each bust is individually fire-patinated and hand-polished by master craftsmen to evoke centuries of quiet temple presence.',
    price: 18200,
    compareAtPrice: 22000,
    category: 'Sculptures',
    categorySlug: 'sculptures',
    collection: 'Sanctuary & Soul',
    images: [
      'https://images.unsplash.com/photo-1569683795645-b62e50fbf103?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=80',
    ],
    model3D: {
      type: 'sculpture',
      color: '#6e543c',
      roughness: 0.42,
      metalness: 0.8,
      scale: 1.05,
    },
    material: 'Aged Bronze with Verdigris & Gold Wash',
    dimensions: '38cm H x 24cm W x 22cm D',
    weight: '9.8 kg',
    origin: 'Kyoto Sanctuary Atelier',
    era: 'Heian Echoes',
    stock: 9,
    rating: 4.9,
    reviewsCount: 52,
    featured: true,
    bestseller: true,
    isNew: false,
    limited: false,
    handcrafted: true,
    tags: ['Buddha', 'Bronze', 'Bestseller', 'Meditation'],
    specifications: {
      'Mount': 'Integrated Bronze Display Collar',
      'Acoustic Felt Base': 'Scratch-resistant underside padding',
    },
  },
  {
    id: 'lux-04',
    name: 'Gilded Lotus Candle Sculpture',
    slug: 'gilded-lotus-candle-sculpture',
    subtitle: 'Hand-Forged Sculptural Brass Petal Luminary',
    description: 'An organic sculptural leaf luminary casting warm golden shadows across dining and lounge settings.',
    longDescription: 'Curving upward like a blossoming sacred lotus petal, this hand-forged solid brass candle sculpture shields flickering flames while multiplying their glow into ambient warmth.',
    story: 'Forged over charcoal kilns, every petal contour is beaten by hand with rounded hammers to create a multifaceted texture that shimmers organically in dim light.',
    price: 9400,
    compareAtPrice: 11500,
    category: 'Table Decor',
    categorySlug: 'table-decor',
    collection: 'Golden Flora',
    images: [
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1000&q=80',
    ],
    model3D: {
      type: 'sculpture',
      color: '#c5a059',
      roughness: 0.25,
      metalness: 0.95,
      scale: 1.0,
    },
    material: 'Hammered Solid Brass & Champagne Gold Leaf',
    dimensions: '29cm H x 18cm W x 15cm D',
    weight: '3.6 kg',
    origin: 'Jaipur Heritage Foundry',
    era: 'Art Deco Biophilic',
    stock: 14,
    rating: 4.8,
    reviewsCount: 29,
    featured: true,
    bestseller: false,
    isNew: false,
    limited: true,
    handcrafted: true,
    tags: ['Lotus', 'Brass', 'Candle', 'Lighting', 'Limited'],
    specifications: {
      'Candle Accommodated': 'Standard pillar candles up to 8cm diameter',
      'Heat Resistance': 'Thermal-tested solid brass alloy',
    },
  },
  {
    id: 'lux-05',
    name: 'Archaic Celestial Wall Mandala',
    slug: 'archaic-celestial-wall-mandala',
    subtitle: 'Intricately Carved Bronze Sun Disc & Astrolabe Frieze',
    description: 'A museum-quality ornamental circular wall disc with concentric geometric carvings and astronomical glyphs.',
    longDescription: 'Measuring over half a meter across, this celestial medallion was designed as a focal anchor for dramatic gallery walls. Intricate relief bands portray solar orbits, sacred geometry, and astrological crests.',
    story: 'Inspired by ancient Hellenistic astrolabes recovered from Mediterranean seafaring vessels, this frieze blends cosmic geometry with rustic antique charm.',
    price: 14800,
    compareAtPrice: 18500,
    category: 'Wall Decor',
    categorySlug: 'wall-decor',
    collection: 'Celestial Relics',
    images: [
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=1000&q=80',
    ],
    model3D: {
      type: 'bowl',
      color: '#9e7b4f',
      roughness: 0.45,
      metalness: 0.75,
      scale: 1.15,
    },
    material: 'Relief-Chased Bronze with Black Iron Ring Frame',
    dimensions: '52cm Diameter x 5cm Depth',
    weight: '8.1 kg',
    origin: 'Alexandria Archives',
    era: 'Byzantine Astronomical',
    stock: 5,
    rating: 4.9,
    reviewsCount: 31,
    featured: true,
    bestseller: false,
    isNew: false,
    limited: false,
    handcrafted: true,
    tags: ['Mandala', 'Wall Decor', 'Bronze', 'Celestial', 'Handcrafted'],
    specifications: {
      'Mounting': 'Concealed heavy-duty steel French cleat included',
      'Orientation': '360-degree rotational mounting freedom',
    },
  },
  {
    id: 'lux-06',
    name: 'Solstice Brass Arc Table Lamp',
    slug: 'solstice-brass-arc-table-lamp',
    subtitle: 'Sculptural Loop Luminaire with Hand-Blown Opal Orb',
    description: 'A modernist antique lamp featuring an arching bronze frame cradling a glowing frosted glass moon sphere.',
    longDescription: 'Melding bauhaus architectural restraint with antique bronze metallurgy, the Solstice Arc Lamp bathes living rooms in warm 2700K ambient illumination. Features an integrated rotary brass dimmer.',
    story: 'Engineered as both functional task light and sculptural desktop objet d art, its seamless curvilinear stem is heat-bent over vintage iron jigs.',
    price: 22000,
    compareAtPrice: 26000,
    category: 'Lighting',
    categorySlug: 'lighting',
    collection: 'Luminous Curves',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1000&q=80',
    ],
    model3D: {
      type: 'sculpture',
      color: '#c5a059',
      roughness: 0.2,
      metalness: 0.9,
      scale: 1.0,
    },
    material: 'Solid Brushed Antique Brass & Hand-Blown Triplex Opal Glass',
    dimensions: '42cm H x 26cm W x 22cm D',
    weight: '5.8 kg',
    origin: 'Milan Design Foundry',
    era: 'Mid-Century Revival',
    stock: 8,
    rating: 4.9,
    reviewsCount: 22,
    featured: false,
    bestseller: false,
    isNew: true,
    limited: false,
    handcrafted: true,
    tags: ['Lighting', 'Lamp', 'Brass', 'Glass', 'Modern Antique'],
    specifications: {
      'Voltage': '110-240V Universal',
      'Bulb': 'G9 Warm LED included (Dimmable)',
      'Cord': '2.2m Twisted Gold Fabric Cable with Inline Rotary Switch',
    },
  },
  {
    id: 'lux-07',
    name: 'Patinated Bronze Ritual Offering Bowl',
    slug: 'patinated-bronze-ritual-offering-bowl',
    subtitle: 'Fluted Pedestal Centerpiece with Hand-Hammered Rim',
    description: 'A substantial low-profile antique bowl with rich dark chocolate patina and subtle bronze edge burnishing.',
    longDescription: 'Ideal as an opulent dining table centerpiece or entryway catchment for treasured heirlooms, this flared bowl rests gracefully upon a stepped circular base with timeless poise.',
    story: 'Crafted following temple libation vessels excavated in the Peloponnese, its low silhouette anchors wide coffee tables with quiet dignity.',
    price: 8900,
    compareAtPrice: 10500,
    category: 'Table Decor',
    categorySlug: 'table-decor',
    collection: 'Sanctuary & Soul',
    images: [
      'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1000&q=80',
    ],
    model3D: {
      type: 'bowl',
      color: '#4f3f2d',
      roughness: 0.5,
      metalness: 0.7,
      scale: 1.1,
    },
    material: 'Sand-Cast Bronze with Chocolate Oil Patina',
    dimensions: '16cm H x 32cm Diameter',
    weight: '4.7 kg',
    origin: 'Crete Guild Workshop',
    era: 'Minoan Echoes',
    stock: 12,
    rating: 4.7,
    reviewsCount: 18,
    featured: false,
    bestseller: false,
    isNew: false,
    limited: false,
    handcrafted: true,
    tags: ['Bowl', 'Table Decor', 'Bronze', 'Centerpiece'],
    specifications: {
      'Food Safe': 'Dry foodstuffs, fruits or decorative objects only',
      'Stability': 'Heavy solid base prevents tipping',
    },
  },
  {
    id: 'lux-08',
    name: 'Imperial Horned Taurus Figurine',
    slug: 'imperial-horned-taurus-figurine',
    subtitle: 'Anatolian Cast Bronze Bull with Muscular Facets',
    description: 'A dynamic modernist bronze bull sculpture celebrating strength, raw determination, and ancient metallurgy.',
    longDescription: 'Showcasing geometric muscular planes and proud upward-swept horns, the Taurus Figurine is a testament to primal power refined into gallery-caliber sculpture.',
    story: 'Referencing 3rd-millennium BCE Anatolian ceremonial standards, this sculpture translates archaic mythology into clean, contemporary living spaces.',
    price: 34000,
    compareAtPrice: 41000,
    category: 'Custom Designs',
    categorySlug: 'custom-designs',
    collection: 'Imperial Heritage',
    images: [
      'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=80',
    ],
    model3D: {
      type: 'sculpture',
      color: '#5e4835',
      roughness: 0.35,
      metalness: 0.88,
      scale: 1.0,
    },
    material: 'Solid Cast Gunmetal Bronze with Hand-Brushed Wax Sealer',
    dimensions: '31cm H x 44cm L x 16cm W',
    weight: '11.5 kg',
    origin: 'Anatolian Guild Archives',
    era: 'Bronze Age Reimagined',
    stock: 2,
    rating: 5.0,
    reviewsCount: 14,
    featured: false,
    bestseller: false,
    isNew: false,
    limited: true,
    handcrafted: true,
    tags: ['Bull', 'Taurus', 'Custom', 'Bronze', 'Collector'],
    specifications: {
      'Edition': 'Limited to 25 signed editions globally',
      'Foundry Mark': 'Individually stamped with Luxignia artisan seal',
    },
  },
];
